;######################################################
;##                Desktop08.ini
;######################################################


;NB: 
; Alcuni settaggi sovrascrivono quelli in Kvara ini,
; in particolare per i font (sezione [DESKFONT] di Kvara ini)
; e per le dimensioni degli elementi del desktop 
; (status bar, bottoni orizzontali, ecc...)


;-------------------------------------------------------
; Abilitazione Desktop 08
;-------------------------------------------------------

[GLOBAL]
ENABLED=1


;-------------------------------------------------------
; Settaggi bottoni orizzontali
;-------------------------------------------------------

[HOR_KEYS]

HEIGHT=90
SYSTEM_KEY_WIDTH=90

;## Default Values

BKG_COLOR=190,190,190
BKG_SEL_COLOR=44,44,44

TXT_COLOR=0,0,0
TXT_SEL_COLOR=255,255,255

BORDER_COLOR=127,127,127
BORDER_COLOR_ACTIVE=0,0,0
BORDER_THICK=1

CUSTOM_KEY_MENU = C:\\Kvara\\icone ppg\\Mainmenu\\Menu.png
CUSTOM_KEY_LEFT  =  C:\\Kvara\\icone ppg\\Mainmenu\\STK_LEFT.png
CUSTOM_KEY_LEFT_OFF  =  C:\\Kvara\\icone ppg\\Mainmenu\\STK_LEFT_OFF.png
CUSTOM_KEY_RIGHT  =  C:\\Kvara\\icone ppg\\Mainmenu\\STK_RIGHT.png
;CUSTOM_KEY_RIGHT_OFF  =  C:\\Kvara\\icone ppg\\Mainmenu\\STK_RIGHT_OFF.png
CUSTOM_KEY_MENU_DIS = C:\\Kvara\\icone ppg\\Mainmenu\\Menu.png

;-------------------------------------------------------
; Settaggi bottoni verticali
;-------------------------------------------------------

[VERT_KEYS]

;Key_Width=75
Key_Width=120

;## Default Values

BKG_COLOR=190,190,190
BKG_SEL_COLOR=44,44,44

TXT_COLOR=0,0,0
TXT_SEL_COLOR=255,255,255

BORDER_COLOR         = 127,127,127
BORDER_COLOR_ACTIVE  = 0,0,0
BORDER_THICK=1

LED_ON=1
LED_EDGE=30


;-------------------------------------------------------
; Font bottoni orizzontali e verticali  (Solo Win)
;-------------------------------------------------------

; >> Font per tasti SENZA bitmap  <<
[PIC_FONT]           
FONT_NAME  = Arial
FONT_HEIGHT= 16
FONT_WIDTH = 6
FONT_BOLD  = 700


;>>  Font per tasti CON bitmap <<
[PICS_FONT]          
FONT_NAME  = Arial
FONT_HEIGHT= 16
FONT_WIDTH = 6
FONT_BOLD  = 700


;-------------------------------------------------------
; Settaggi Status Bar
;-------------------------------------------------------

[STATUS_BAR]
HEIGHT=58
BKG_COLOR=190,190,190

BKG_COLOR_TIME=60,111,190
TXT_COLOR_TIME=

BKG_COLOR_ALARM=190,190,190
TXT_COLOR_ALARM1=255,0,0
TXT_COLOR_ALARM2=255,0,0
TXT_COLOR_MSG=0,0,255

BKG_COLOR_CAPTION=190,190,190
TXT_COLOR_CAPTION=

BKG_COLOR_ICON=190,190,190

;LOGO_FILE_BMP=C:\Kvara\Logo58x48.png
;-------------------------------------------------------
; Font Status Bar (solo Win)
;-------------------------------------------------------

[CAPTION_FONT]
FONT_NAME  = Arial
FONT_HEIGHT= 34
;FONT_WIDTH = 8
FONT_BOLD  = 800


[ALARMS_FONT]
FONT_NAME  = Arial
FONT_HEIGHT= 18
FONT_WIDTH = 12
FONT_BOLD  = 800


;-------------------------------------------------------
; Settaggi System Menu
;-------------------------------------------------------

[SYSTEM_MENU]

SYS_WIDTH=300

BKG_COLOR=190,190,190
BKG_SEL_COLOR=44,44,44


;** Colori Sys Menu (Sfondo, bordo e testo)
SYS_BKG_NORM_COLOR = 190,190,190  
SYS_EDG_NORM_COLOR = 127,127,127
SYS_TXT_NORM_COLOR = 44,44,44
SYS_BKG_SEL_COLOR  = 128,128,128
SYS_EDG_SEL_COLOR  = 0,0,0    
SYS_TXT_SEL_COLOR  = 44,44,44  


;** Colori Menu Contestuale (Sfondo, bordo e testo)
APP_BKG_NORM_COLOR = 190,190,190
APP_EDG_NORM_COLOR = 127,127,127
APP_TXT_NORM_COLOR = 44,44,44
APP_BKG_SEL_COLOR  = 128,128,128
APP_EDG_SEL_COLOR  = 0,0,0    
APP_TXT_SEL_COLOR  = 44,44,44  


[SYSMENU_FONT]
FONT_NAME  = Arial
FONT_HEIGHT= 26
FONT_WIDTH = 9
FONT_BOLD  = 500


// Utilizzati solo su monoboard

;-------------------------------------------------------
; Settaggi Status Bar di pagina
;-------------------------------------------------------

[STATUS_BAR_PAGE]
BKG_COLOR= 240,240,240
TXT_COLOR= 255,255,255

;-------------------------------------------------------
; Settaggi colore sfondo pagine di base
;-------------------------------------------------------

[DESK_PAGE]
BKG_COLOR=

;-------------------------------------------------------
; Settaggi colori dialog modali
;-------------------------------------------------------

[DESK_DIALOG]
BKG_COLOR=
TXT_COLOR=
BKG_COLOR_KEY=
TXT_COLOR_KEY=

BKG_COLOR_RECT_SELKEY=
BKG_COLOR_SELKEY=
TXT_COLOR_SELKEY=