* I/O fisici
* Ingressi

#defcom %FUNCBTN.0  Pulsante start
#defcom %FUNCBTN.1  Pulsante stop
#defcom %FUNCBTN.2  Pulsante +
#defcom %FUNCBTN.3  Pulsante -

#defcom %C60.0    IN Pedale discesa
#defcom %C60.1    IN Pedale salita
#defcom %C60.2    IN Intervento fotocellula
#defcom %C60.3    IN Abilitazione accompagnatori
#defcom %C60.4    IN Salita manuale lenta
#defcom %C60.5    IN Fotocellule escluse
#defcom %C60.6    IN Emergenza generale
#defcom %C60.7    IN Modo risalita
#defcom %C60.8    IN Macchina remota in automatico
#defcom %C60.9    IN Macchina remota in semiautomatico
#defcom %C60.10   IN Pulsante START esterno
#defcom %C60.11   IN Apertura al PMS massimo
#defcom %C60.12   IN Reset lavorazione
#defcom %C60.13   IN Funzionamento con robot
#defcom %C60.14   IN Selezione macchina in tandem
#defcom %C60.15   IN Macchina remota al PMS
#defcom %C60.16   IN Macchina remota al PCV
#defcom %C60.17   IN Macchina remota al PCL
#defcom %C60.18   IN Macchina remota al PMI
#defcom %C60.19   IN Macchina remota al PCL prima del rinculo
#defcom %C60.20   IN Assi in posizione CN remoto
#defcom %C60.21   IN Macchina remota in allarme
#defcom %C60.22   IN Pulsante STOP esterno
#defcom %C60.23   IN OPS bombatura in corso
#defcom %C60.24   IN Sel. apertura bloccaggi inferiori
#defcom %C60.25   IN OID indice in corso
#defcom %C60.26   IN Taratura sensori GPS
#defcom %C60.27   IN Sel. apertura bloccaggi superiori
#defcom %C60.28   IN Cambio passo (pressa tradizionale o robot)
#defcom %C60.29   IN Micro rinculo (pressa tradizionale)
#defcom %C60.30   IN Micro PMS (pressa tradizionale e ciclo zeta man)
#defcom %C60.31   IN Selez. abil. ciclo Zeta manuali

#defcom %C61.0    IN Mancanza aria NO
#defcom %C61.1    IN bit 0 codice allarmi
#defcom %C61.2    IN bit 1 codice allarmi
#defcom %C61.3    IN bit 2 codice allarmi
#defcom %C61.4    IN bit 3 codice allarmi
#defcom %C61.5    IN allarme Intervento Termico Pompa
#defcom %C61.6    IN allarme Azionamento asse X
#defcom %C61.7    IN allarme Azionamento asse R
#defcom %C61.8    IN allarme Azionamento asse Z1
#defcom %C61.9    IN allarme Azionamento asse Z2
#defcom %C61.10   IN allarme Filtro Olio Intasato
#defcom %C61.11   IN Pulsante + esterno
#defcom %C61.12   IN Pulsante - esterno
#defcom %C61.13   IN Abil. accompagnatore A2
#defcom %C61.14   IN Mancanza aria NC
#defcom %C61.15   IN Puls. abil. volantino da encoder
#defcom %C61.16   IN NC Forza Velocità di sicurezza Riscontri (2m/min)
#defcom %C61.17   IN 49
#defcom %C61.18   IN Massimo sbilanciamento
#defcom %C61.19   IN Direzione EV Y1 salita
#defcom %C61.20   IN Direzione EV Y2 salita
#defcom %C61.21   IN Direzione EV Y1 discesa
#defcom %C61.22   IN Direzione EV Y2 discesa
#defcom %C61.23   IN Selettore in posizione Manuale
#defcom %C61.24   IN Emergenza discesa
#defcom %C61.25   IN Blocco ciclo da robot
#defcom %C61.26   IN Pressostato bloccaggi superiori
#defcom %C61.27   IN Pressostato bloccaggi inferiori
#defcom %C61.28   IN Monitoraggio relé 20KA1,2,3,4
#defcom %C61.29   IN Trasduttore EV A1
#defcom %C61.30   IN Trasduttore EV A2
#defcom %C61.31   IN Reset PCL e PMI

#defcom %C62.0    IN Pompa Accesa
#defcom %C62.1    IN Cancelli laterali non chiusi
#defcom %C62.2    IN Monitoraggio Trasduttore SQ1
#defcom %C62.3    IN Monitoraggio Trasduttore SQ2 
#defcom %C62.4    IN Selezione pagina impostazioni da robot
#defcom %C62.5    IN Selezione pagina automatico da robot
#defcom %C62.6    IN Bit0 codice programma da robot
#defcom %C62.7    IN Bit1 codice programma da robot
#defcom %C62.8    IN Bit2 codice programma da robot
#defcom %C62.9    IN Bit3 codice programma da robot
#defcom %C62.10   IN Bit4 codice programma da robot
#defcom %C62.11   IN Azionamenti OK
#defcom %C62.12   IN Fine pressata 1
#defcom %C62.13   IN Fine pressata 2
#defcom %C62.14   IN PCV (mute)
#defcom %C62.15   IN Stop at mute
#defcom %C62.16   IN Selezione pagina automatico da tandem
#defcom %C62.17   IN Monitor EV DiscVel SQ5
#defcom %C62.18   IN Monitor EV DiscVel SQ6
#defcom %C62.19   Allarme Utente 1
#defcom %C62.20   Allarme Utente 2
#defcom %C62.21   Allarme Utente 3
#defcom %C62.22   Messaggio Utente 1
#defcom %C62.23   Messaggio Utente 2
#defcom %C62.24   IN Monitor EV Prerimpimenti SQ7
#defcom %C62.25   IN EV Y1 a riposo
#defcom %C62.26   IN EV Y2 a riposo
#defcom %C62.27   IN Monitor EV DiscLen SD
#defcom %C62.28   IN Stop galleggiamento da sensore
#defcom %C62.29   IN Micro taratura pestone NVEL o sola lettura
#defcom %C62.30   IN Selezione pagina manuale da tandem
#defcom %C62.31   IN Selezione pagina semiautomatico da tandem

#defcom %C63.0    IN Selez. secondo PCV
#defcom %C63.1    IN 97
#defcom %C63.2    IN 98
#defcom %C63.3    IN 99
#defcom %C63.4    IN Bit5 codice programma da robot
#defcom %C63.5    IN Bit6 codice programma da robot
#defcom %C63.6    IN Bit7 codice programma da robot
#defcom %C63.7    IN Enable Hand Wheel x10 (0.1mm)
#defcom %C63.8    IN Enable Hand Wheel x100 (1mm)
#defcom %C63.9    IN Enable Hand Wheel Acquisition
#defcom %C63.10   IN Selezione Y1 da Volantino
#defcom %C63.11   IN Selezione Y2 da Volantino
#defcom %C63.12   IN 108
#defcom %C63.13   IN 109
#defcom %C63.14   IN 110
#defcom %C63.15   IN 111
#defcom %C63.16   IN 112
#defcom %C63.17   IN 113
#defcom %C63.18   IN 114
#defcom %C63.19   IN 115
#defcom %C63.20   IN 116
#defcom %C63.21   IN 117
#defcom %C63.22   IN 118
#defcom %C63.23   IN 119
#defcom %C63.24   IN 120
#defcom %C63.25   IN 121
#defcom %C63.26   IN 122
#defcom %C63.27   IN 123
#defcom %C63.28   IN 124
#defcom %C63.29   IN 125
#defcom %C63.30   IN 126
#defcom %C63.31   IN 127

#defcom %C64.0    IN 128
#defcom %C64.1    IN 129
#defcom %C64.2    IN 130
#defcom %C64.3    IN 131
#defcom %C64.4    IN 132
#defcom %C64.5    IN 133
#defcom %C64.6    IN 134
#defcom %C64.7    IN 135
#defcom %C64.8    IN 136
#defcom %C64.9    IN 137
#defcom %C64.10   IN 138
#defcom %C64.11   IN 139
#defcom %C64.12   IN 140
#defcom %C64.13   IN 141
#defcom %C64.14   IN 142
#defcom %C64.15   IN 143
#defcom %C64.16   IN 144
#defcom %C64.17   IN 145
#defcom %C64.18   IN 146
#defcom %C64.19   IN 147
#defcom %C64.20   IN 148
#defcom %C64.21   IN 149

#defcom %C64      IN configurabili (i primi 21 bit)

* Ingressi analogici

#defcom %C68      (IW20) Strain gauge left side (0-4095) o pedale pot.
#defcom %C69      (IW21) Strain gauge right side (0-4095)

#defcom %C82      IN Sensore pressione Cilindro 1
#defcom %C83      IN Sensore pressione Cilindro 2
#defcom %C84      IN Sensore pressione Pompa principale

#defcom %C95      IN (IW90) Posizione cursore valvola Y1 (0-4095)
#defcom %C96      IN (IW91) Posizione cursore valvola Y2 (0-4095)
#defcom %C97      IN Sensore pressione Bombatura

* Uscite

#defcom %C70.0    OUT funzione 1
#defcom %C70.1    OUT funzione 2 (schiaccia pneum./cambio passo al PMS)
#defcom %C70.2    OUT funzione 3 (rinculo assi Z)
#defcom %C70.3    OUT funzione 4 (ciclo sgancio accomp.)
#defcom %C70.4    OUT CNC in automatico
#defcom %C70.5    OUT CNC in semiautomatico
#defcom %C70.6    OUT CNC in manuale
#defcom %C70.7    OUT CNC OK
#defcom %C70.8    OUT Configurazione valvole bit 0
#defcom %C70.9    OUT Configurazione valvole bit 1
#defcom %C70.10   OUT Configurazione valvole bit 2
#defcom %C70.11   OUT Configurazione valvole bit 3
#defcom %C70.12   OUT Configurazione valvole bit 4
#defcom %C70.13   OUT Configurazione valvole bit 5
#defcom %C70.14   OUT Configurazione valvole bit 6
#defcom %C70.15   OUT Configurazione valvole bit 7
#defcom %C70.16   OUT Macchina al PMS
#defcom %C70.17   OUT Macchina al PCV
#defcom %C70.18   OUT Macchina al PCL
#defcom %C70.19   OUT Macchina al PMI
#defcom %C70.20   OUT Macchina al PCL prima del rinculo
#defcom %C70.21   OUT Assi in posizione
#defcom %C70.22   OUT CN in allarme
#defcom %C70.23   OUT Bit0 codice programma per robot
#defcom %C70.24   OUT Bit1 codice programma per robot
#defcom %C70.25   OUT Bit2 codice programma per robot
#defcom %C70.26   OUT Bit3 codice programma per robot
#defcom %C70.27   OUT Bit4 codice programma per robot
#defcom %C70.28   OUT Attivazione RALL
#defcom %C70.29   OUT Attivazione POS
#defcom %C70.30   OUT Attivazione IND
#defcom %C70.31   OUT Attivazione DCP

#defcom %C71.0    OUT Attivazione forchette
#defcom %C71.1    OUT Punzoni sbloccati
#defcom %C71.2    OUT Valvola sblocco Z manuali
#defcom %C71.3    OUT Valvola on-off di pressione A1-A2
#defcom %C71.4    OUT Valvola on-off discesa A1-A2
#defcom %C71.5    OUT controllo syncro
#defcom %C71.6    OUT Pezzi finiti
#defcom %C71.7    OUT Matrici sbloccate
#defcom %C71.8    OUT Escludi fotocellule 5mm prima del PCL
#defcom %C71.9    OUT Blocco Pestone in sola lettura
#defcom %C71.10   OUT Selezione pagina impostazioni per robot
#defcom %C71.11   OUT Selezione pagina automatico per robot
#defcom %C71.12   OUT CNC ready down (discesa pestone abilitata)
#defcom %C71.13   OUT UP command LZS (salita)
#defcom %C71.14   OUT Decompressione in corso
#defcom %C71.15   OUT CNC in autotuning
#defcom %C71.16   OUT Velocità lenta in salita
#defcom %C71.17   OUT Velocità lentissima
#defcom %C71.18   OUT Spia bloccaggi superiori aperti
#defcom %C71.19   OUT Spia bloccaggi inferiori aperti
#defcom %C71.20   OUT Spia fotocellule escluse
#defcom %C71.21   OUT EV pressione cuscino idraulico
#defcom %C71.22   OUT Pilotaggio EV bombatura
#defcom %C71.23   OUT Uscita pulsante di START
#defcom %C71.24   OUT Uscita pulsante di STOP
#defcom %C71.25   OUT Uscita pulsante +
#defcom %C71.26   OUT Uscita pulsante -
#defcom %C71.27   OUT Abilitazione discesa
#defcom %C71.28   OUT Accompagnamento in corso
#defcom %C71.29   OUT Opz. gestione procedura spazio d'arresto
#defcom %C71.30   OUT Opz. gestione bloccaggi superiori
#defcom %C71.31   OUT Opz. gestione bloccaggi inferiori

#defcom %C72.0    OUT Errore monitoraggio valvole proporzionali
#defcom %C72.1    OUT Opz. gestione bloccaggi superiori 2
#defcom %C72.2    OUT Opz. gestione Fiessler
#defcom %C72.3    OUT Opz. gestione doppia pedaliera
#defcom %C72.4    OUT Opz. gestione accompagnatori
#defcom %C72.5    OUT Funzione 5 (discesa lenta)
#defcom %C72.6    OUT Funzione 6 (selezione pedaliera sinistra)
#defcom %C72.7    OUT Funzione 7 (sistema sicurezza Fiessler)
#defcom %C72.8    OUT Funzione 8 (tipo bombatura)
#defcom %C72.9    OUT Funzione 9 (Cambio Passo a Fine Piega)
#defcom %C72.10   OUT Funzione 10
#defcom %C72.11   OUT Funzione 11
#defcom %C72.12   OUT Funzione 12
#defcom %C72.13   OUT Funzione 13
#defcom %C72.14   OUT Funzione 14
#defcom %C72.15   OUT Funzione 15
#defcom %C72.16   OUT Funzione 16
#defcom %C72.17   OUT Funzione 17
#defcom %C72.18   OUT Funzione 18
#defcom %C72.19   OUT Funzione 19
#defcom %C72.20   OUT Funzione 20
#defcom %C72.21   OUT Massimo sbilanciamento
#defcom %C72.22   OUT Sosta per tempo piega in corso
#defcom %C72.23   OUT Salita al PMS in corso (tradiz.)
#defcom %C72.24   OUT Fine decompressione
#defcom %C72.25   OUT Valvola Blocco Punzoni
#defcom %C72.26   OUT Valvola Blocco Matrici
#defcom %C72.27   OUT Macchina tarata
#defcom %C72.28   OUT Funzione matrice F1
#defcom %C72.29   OUT Funzione matrice F2
#defcom %C72.30   OUT Funzione matrice F3
#defcom %C72.31   OUT Funzione matrice F4

#defcom %C73.0   OUT  Funzione matrice F5
#defcom %C73.1   OUT  Funzione matrice F6
#defcom %C73.2   OUT  Ciclo attivo
#defcom %C73.3   OUT  Ciclo non attivo
#defcom %C73.4    OUT Pompa On OUT 100
#defcom %C73.5    OUT Secondo Mute (Akas3pm) OUT 101
#defcom %C73.6    OUT Bit5 codice programma per robot OUT 102
#defcom %C73.7    OUT Bit6 codice programma per robot OUT 103
#defcom %C73.8    OUT Bit7 codice programma per robot OUT 104
#defcom %C73.9    OUT 105
#defcom %C73.10   OUT 106
#defcom %C73.11   OUT 107
#defcom %C73.12   OUT 108
#defcom %C73.13   OUT 109
#defcom %C73.14   OUT 110
#defcom %C73.15   OUT 111
#defcom %C73.16   OUT 112
#defcom %C73.17   OUT 113
#defcom %C73.18   OUT 114
#defcom %C73.19   OUT 115
#defcom %C73.20   OUT 116
#defcom %C73.21   OUT 117
#defcom %C73.22   OUT 118
#defcom %C73.23   OUT 119
#defcom %C73.24   OUT 120
#defcom %C73.25   OUT 121
#defcom %C73.26   OUT 122
#defcom %C73.27   OUT 123
#defcom %C73.28   OUT 124
#defcom %C73.29   OUT 125
#defcom %C73.30   OUT 126
#defcom %C73.31   OUT 127

#defcom %C93.0    OUT 128
#defcom %C93.1    OUT 129
#defcom %C93.2    OUT 130
#defcom %C93.3    OUT 131
#defcom %C93.4    OUT 132
#defcom %C93.5    OUT 133
#defcom %C93.6    OUT 134
#defcom %C93.7    OUT 135
#defcom %C93.8    OUT 136
#defcom %C93.9    OUT 137
#defcom %C93.10   OUT 138
#defcom %C93.11   OUT 139
#defcom %C93.12   OUT 140
#defcom %C93.13   OUT 141
#defcom %C93.14   OUT 142
#defcom %C93.15   OUT 143
#defcom %C93.16   OUT 144
#defcom %C93.17   OUT 145
#defcom %C93.18   OUT 146
#defcom %C93.19   OUT 147
#defcom %C93.20   OUT 148
#defcom %C93.21   OUT 149

* Uscite analogiche

#defcom %C74      OUT (QW207) Comando corrente Y1 discesa
#defcom %C75      OUT (QW209) Comando corrente Y2 discesa
#defcom %C76      OUT (QW206) Comando corrente Y1 salita
#defcom %C77      OUT (QW208) Comando corrente Y2 salita

#defcom %C78      OUT (QW100) Comando pressione
#defcom %C79      OUT (QW101) Comando bombatura
#defcom %fs0      OUT (QW200) Fondo scala comando pressione
#defcom %fs1      OUT (QW201) Fondo scala comando bombatura

#defcom %C85      OUT (QW210) Frequenza PWM

#defcom %C86      OUT (QW211) Uscita simulata valvola Y1 da slave (14 bit + direzioni)
#defcom %C87      OUT (QW212) Uscita simulata valvola Y2 da slave (14 bit + direzioni)
#defcom %C88      OUT (QW204) Comando valvola Y1 (14 bit + direzioni)
#defcom %C89      OUT (QW205) Comando valvola Y2 (14 bit + direzioni)

#defcom %C93      OUT configurabili (i primi 21 bit)
