[APP]
WorkDir=\Kvfile\Prg\
MatDir=\Kvfile\Mat\
PnzDir=\Kvfile\Pnz\
Prod=KVARA2000
Font=1
BackupUnit=E:
WorkDrive=C:
MANUAL_BACK_GAUGE=1
TOOLBAR=1
SHOW_SEQ_PIEGA=1
ICONVERSION=1
Reread_ParDat=1
WS_BORDER=0
TOOLBAR_ICON=2
ICONDIR=..\icone ppg\
TAB_MAT=1
DieHolderDrive=..\..
DieHolderDir=\Kvfile\DieHolder\
IntermediateDrive=..\..
IntermediateDir=\Kvfile\Intermediate\
MatDrive=..\..
PnzDrive=..\..
HMI=TOUCH
KVARADB=1
;EXT_FILE_PROG_ADD=3d
PDF=C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe
LAYOUT_IMP_MAN_SAUTO_AUTO=NORM

;Pice set. Cad2D: Ray, Thickness, Drawing on the left 
WORKPIECE_CAD2D=1

;Automatic Sequence: Ray
WORKPIECE_OTT=1

;Calendering Exp
CAL_EXP=1
CHECK_UI_CNC=1
CAM3D=C:\\Program Files\Esautomotion\\EsaBend3D.11\\Program\\MBTerminal.exe
EXPAND_CAL=0
GO_AUTO=1
LIST_PROG_FROM_BARCODE=0
CORR=RENEWED


[START]
DEBUG=
PROG=7051
progp=999
pieceflista=22481395
piecedlista=22481437
LISTA_PROGRAMMI=1

[COLOR]
CRFORE=0
CRBACK=14671839
CRFOREFOC=4539717
CRBACKFOC=65408
CRFOREDIS=0
CRBACKDIS=16777215
CRFOREDIS2=0
CRBACKDIS2=16777088
AUTO=COL
TITLEFGB=8421504
TITLEBGB=8421504
PROMPT=16777215

[FONT_STATIC]
NAME  =Roman
HEIGHT=-16
WIDTH =0
BOLD  =700

[FONT_STATIC_TOUCH_EDITOR_PAGE]
NAME  =MS Sans Serif
HEIGHT=-24
WIDTH =0
BOLD  =700

[FONT_EDIT_TOUCH_EDITOR_PAGE]
NAME  =MS Sans Serif
HEIGHT=-32
WIDTH =0
BOLD  =700


[EDIT]
FLAT=1

[BACKGROUND]
COLOR=4210752
GRAD=2
WORKPICECAD_COLOR=15827310
;BIT_MAP=1

[DEFAULT]
PAG_ABILITATA=0

[SystemInfo]
;Model=#LS

[Sensore Angolo]
Modo Operativo=0
IntNumPezzi=1

[SENSOR_LC]
Log_file=0

; Se a 1 alla partenza di Ppg.exe viene mandato in esecuzione il programma indicato nella chiave LaserCheck=
; Default 1
;StartLaserCheck=1
                               
; Programma LaserCheck avviato alla partenza di Ppg.exe se la chiave StartLaserCheck vale 1
;LaserCheck=C:\LaserCheck\LaserCheck.exe

; Se a 1 alla partenza di Ppg.exe viene fatta partire la comunicazione tra Ppg.exe e il programma LaserCheck
; Default 1
;StartCommToLaserCheck=1

[Pressione]
ActBomb=0

[BUTTON COLOR]
crForeButton=118,118,118
crBackButton=51,51,51
crForeDisButton=0,0,0
crBackDisButton=0,0,0
crForeSelButton=0,0,0
crBackSelButton=153,153,153


[POOUP COLOR]
cBkgItemPopupMenu=32,32,32
cTxtItemPopupMenu=204,204,204
cBkgSelItemPopupMenu=153,153,153
cTxtSelItemPopupMenu=0,0,0
cBordoItemNormPopupMenu=32,32,32
cBordoItemSelPopupMenu=153,153,153

[ModBusTCPClient]
Enable=1
Extension=0
NO_AUTO=1
NODEID=2
IPADDR=127.0.0.1
PORT=7172
COMMAND=652
ACK_COMMAND=82
NAME_PROG=653
NEWPROG=BIT_0
LOADPROG=BIT_1
[WORKPICE_CAD2D]
MODE_CAL=0
[F_MACCH_DLG]
X_POS=356
Y_POS=169
