[OPTIONS]

Background=RGB(0,0,255)
BiosExt=1
Diskmon=1
LdrExe=1
FirstOp=0
Select=1
StartPLC=1
DontKill=0
Exclude=8
;Include=0,1
NoLanguage=1

[Configuration.0]

; Nome configurazione
Name=LX800

; Condizioni da soddisfare
RequiredComponent0=CpuModel
RequiredVersion0=100
ActivationCondition0=EQ

; path rtos.ini di questa configurazione
RtosINI=..\CPU\LX800\DiscoC

BootLoader=..\CPU\LX800\Tar\Bootldr.bin

; path DiscoC di questa configurazione
DiscoC=..\CPU\LX800\DiscoC

[Configuration.1]
Name=EDEN

RequiredComponent0=CpuModel
RequiredVersion0=200
ActivationCondition0=EQ

BootLoader=..\CPU\EDEN\Tar\Bootldr.bin
RtosINI=..\CPU\EDEN\DiscoC
DiscoC=..\CPU\EDEN\DiscoC

[Configuration.2]
Name=EDEN_2_RTL

RequiredComponent0=CpuModel
RequiredVersion0=210
ActivationCondition0=EQ

BootLoader=..\CPU\EDEN_2_RTL\Tar\Bootldr.bin
RtosINI=..\CPU\EDEN_2_RTL\DiscoC
DiscoC=..\CPU\EDEN_2_RTL\DiscoC
