[APP]
WorkDir=\Kvfile\Prg\
MatDir=\Kvfile\Mat\
PnzDir=\Kvfile\Pnz\
Prod=KVARA2000
Font=1
BackupUnit=D:
WorkDrive=C:
MANUAL_BACK_GAUGE=1
TOOLBAR=1
SHOW_SEQ_PIEGA=1
;CAM=AutoPOL
ICONVERSION=1
Reread_ParDat=1
WS_BORDER=0
TOOLBAR_ICON=2
ICONDIR=c:\Kvara\icone ppg\
TAB_MAT=1
DieHolderDrive=C:
DieHolderDir=C:\Kvfile\DieHolder\
IntermediateDrive=C:
IntermediateDir=C:\Kvfile\Intermediate\
MatDrive=C:
PnzDrive=C:
EXPAND_CAL=0
HMI=TOUCH
LAYOUT_IMP_MAN_SAUTO_AUTO=RENEWED

;EXT_FILE_PROG_ADD=3d
PDF=C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe
WORKPIECE_CAD2D=0


[START]
DEBUG=
PROG=
progp=999
pieceflista=0
piecedlista=0
LISTA_PROGRAMMI=0

[COLOR]
CRFORE=0
CRBACK=14811135
CRFOREFOC=14811135
CRBACKFOC=8388608
CRFOREDIS=8388608
CRBACKDIS=8421504
CRFOREDIS2=8388608
CRBACKDIS2=8454143
AUTO=COL
TITLEFGB=8421504
TITLEBGB=8421504

[FONT_STATIC]
NAME  =MS Sans Serif
HEIGHT=-16
WIDTH =0
BOLD  =700

[FONT_STATIC_TOUCH_EDITOR_PAGE]
NAME  =MS Sans Serif
HEIGHT=-24
WIDTH =0
BOLD  =700

[FONT_EDIT_TOUCH_EDITOR_PAGE]
NAME  =MS Sans Serif
HEIGHT=-32
WIDTH =0
BOLD  =700


[EDIT]
FLAT=1

[BACKGROUND]
COLOR=12632256
GRAD=2
;BIT_MAP=1

[DEFAULT]
PAG_ABILITATA=0

[SystemInfo]
;Model=#LS

[Sensore Angolo]
Modo Operativo=0
IntNumPezzi=1

[SENSOR_LC]
Log_file=0  

; Se a 1 alla partenza di Ppg.exe viene mandato in esecuzione il programma indicato nella chiave LaserCheck=
; Default 1
;StartLaserCheck=1
                               
; Programma LaserCheck avviato alla partenza di Ppg.exe se la chiave StartLaserCheck vale 1
;LaserCheck=C:\LaserCheck\LaserCheck.exe

; Se a 1 alla partenza di Ppg.exe viene fatta partire la comunicazione tra Ppg.exe e il programma LaserCheck
; Default 1
;StartCommToLaserCheck=1

[Pressione]
ActBomb=0

[BUTTON COLOR]
;crForeButton=118,118,118
;crBackButton=51,51,51
;crForeDisButton=0,0,0
;crBackDisButton=0,0,0
;crForeSelButton=0,0,0
crBackSelButton=44,44,44


[POOUP COLOR]
cBkgItemPopupMenu=190,190,190
cTxtItemPopupMenu=0,0,0
cBkgSelItemPopupMenu=44,44,44
cTxtSelItemPopupMenu=255,255,255
cBordoItemNormPopupMenu=127,127,127
cBordoItemSelPopupMenu=0,0,0

[ModBusTCPClient]
Enable=1
Extension=0
NO_AUTO=0
NODEID=2
IPADDR=127.0.0.1
PORT=7172
COMMAND=652
ACK_COMMAND=82
NAME_PROG=653
NEWPROG=BIT_0
LOADPROG=BIT_1
