[APP]
WorkDir=\Kvfile\Prg\
MatDir=\Kvfile\Mat\
PnzDir=\Kvfile\Pnz\
Prod=KVARA2000
Font=1
BackupUnit=D:
WorkDrive=C:
MANUAL_BACK_GAUGE=1
;TOOLBAR=1
SHOW_SEQ_PIEGA=0
;CAM=AutoPOL
ICONVERSION=1
Reread_ParDat=1
WS_BORDER=0
;KVARADB=1
;TOOLBAR_ICON=2
ICONDIR=c:\Kvara\icone ppg\
TAB_MAT=1
WORKPIECE_CAD2D=0

[START]
DEBUG=
PROG=12345
progp=999
pieceflista=0
piecedlista=0
LISTA_PROGRAMMI=0

[COLOR]
CRFORE=0
CRBACK=14811135
CRFOREFOC=14811135
CRBACKFOC=8388608
CRFOREDIS=8388608
CRBACKDIS=8421504
CRFOREDIS2=8388608
CRBACKDIS2=8454143
AUTO=COL
TITLEFGB=8421504
TITLEBGB=8421504

[FONT_STATIC]
NAME  =MS Sans Serif
HEIGHT=-16
WIDTH =0
BOLD  =700

[EDIT]
FLAT=1

[BACKGROUND]
COLOR=12632256
GRAD=2
;BIT_MAP=1

[DEFAULT]
PAG_ABILITATA=0

[SystemInfo]
;Model=#LS

[Sensore Angolo]
Modo Operativo=0
IntNumPezzi=1

[SENSOR_LC]
Log_file=0


[Pressione]
ActBomb=0
