;
; These are application specifics
;

[Environment]
; Environment variables may be specified here.
; _KERNEL_=ETS *MUST* be specified when operating in a Kvara System.
_KERNEL_=ETS
ETS=YES
ETS-ENV=RTOS.INI

[PEG]
XRes=800
YRes=600
Bpp=16
ForceBPP=False
DriverSignature=0
UseBIOS=True
ThreadPriority=0
StackSize=32768
TimerPeriod=10
Mouse=True
Keyboard=True
MessageQueueSize=40
SmallScrollButton=False
AutoShutdown=True
RestoreVideoMode=True

[Serial.COM4]
;IRQ=10
FIFO=Yes
BaudRate=9600
Parity=None
DataBits=8
StopBits=1
HWFlowControl=No
SWFlowControl=No
AssertOnOpen=Yes

[mouse]
MousePort=PS2

[TouchScreen]
;Controller=SmartSet
;Port=COM4

[NetworkDevices.ether0]
AdapterType=Rtl81x9
;AdapterType=i8255x
;AdapterType=Ne2k
;da usare con Ne2k:
;Base=300
;IRQ=5

[Profiles]
TCPIP=TcpIp.Ini
;TouchScreen.Preferences=TouchScreen-Preferences.Ini
;TouchScreen.Calibration=TouchScreen-Calibration.Ini
InfoMachineNetwork=C:\Machine.ini
InfoResourcesMachine=D:\Resources.ini

[SysTerminal]
;VGAmode=1
;Display=2
Keyboard=3

[Components.Version]
CpuModel=200