[SYS]
DEFCN=..\DiscoC\discoh
IOREDIR=..\DiscoC\discoh
CNIOREDIR=C:\DiscoH
LINK=NETWORK
DATA=..\..\dati
PERMISSION=APPLICATION

[PLC]
SIMDIR=..\Plc\tar
TARDIR=c:\plc

[SIMULATO]
Parametri=1

[CHA.PATH]
PGM=..\DiscoC\PGM
CFS=..\DiscoC\CFU
CFU=..\DiscoC\CFU
CFCDLL=..\DiscoC\AUTODLL
CVBDLL=$
APIODLL=$
PMIDLL=$
SLAPPG=..\DiscoC\AUTODLL\slappg.dll
SLAOSC=..\DiscoC\AUTODLL\slaosc.dll
SLACOUP=..\DiscoC\AutoDll\Slacoup.dll
USERDLL=..\DiscoC\AUTODLL

[CHA.EXT]
PGM=PGM
CFU=CFU
CFS=CFS

[GLOBAL]
Language=ENG
Mouse=ON
LogoWait=..\exe\Splashppg.bmp
Dimensions=1024x600
FunKeyRedir=NH
AlarmFile=..\exe\AlrData.alm
AlarmViewHistoryStartup=1
StartDrvKey500=1
FunKeyRedirPPG=1
;VIRTKEYB=CIRILLO.EXE
TOUCHSCREEN=1
InitFile=
Background=
Template=
PegProject=
ScrollAlarms=1
HideMenu=1

;No bordo 3d alla frame
BorderPage3DLook=0


[ENV]
LOG=..

[UIM.PATH]
CFG=..\..\dati;..\..\DatiPpg;..\..\DatiPpg\CustomKeys
DATA=..\..\dati\par
HISTORY=..\..\dati\par
PLCERR=..\..\dati
PLCMSG=..\..\dati
RUNERR=..\..\dati
PHIERR=..\..\dati
USERFUNDIR=
HOSTFUNDIR=
PIC=..\..\dati;..\Bitmap;..\icone ppg\alphabet;..\icone ppg\Numeric Editor;..\icone ppg\Editor & Sub menu;..\icone ppg\Common;..\icone ppg\JOG

[LoadApp]
Slave=..\exe\sim32 /0G /A40
NCrun=..\exe\ncrun /L-
PLC=..\exe\lnk
ShDump=..\exe\shdump /HIDE /F:A:shdump.gz

[APP]
DISCOH=..\tar
DISCOFPLC=..\plc
DISCOFISO=..\iso
VERT_TOOLBAR=1
TOUCH_TOOLBAR=1
ShowStartStopPlusMinusBtn=1

[CHMONITOR]
FPAXE=..\..\dati\parax.str         
FNAXE=..\..\dati\parax?.nam          
KEYPADRE=KEY_SYSPARAX
KEYASSI=KEY_PARAX

[AUTOSETUP]
IniFILE=..\exe\AutoSetup.ini
;BootLoader=..\Tar\Bootldr.bin
DiscoC=..\DiscoC
PlcProj=..\Plc\plc.kva
;PlcBckp=..\DiscoI
SysMenuIniFile=..\exe\SysMenuFile.ini

[COM] 
CHKDATA=H:\NULLO
MODEM=0
WAITENDSYNC=1000
WAITINITSYNC=1000
WAITRESETINIT=3000
WAITRESETSYNC=3000
IPAddr=10.10.51.100

[PPTCPSERVER]
NODEID=1
IPADDR=127.0.0.1
PORT=502
MAX_COIL=32
MAX_HOLDING_REGISTER=1024
;LOG=C:\PPTCPServer.Log		; log file per debug 
