;######################################################
;##                Desktop08.ini
;######################################################


;NB: 
; Alcuni settaggi sovrascrivono quelli in Kvara ini,
; in particolare per i font (sezione [DESKFONT] di Kvara ini)
; e per le dimensioni degli elementi del desktop 
; (status bar, bottoni orizzontali, ecc...)


;-------------------------------------------------------
; Abilitazione Desktop 08
;-------------------------------------------------------

[GLOBAL]
ENABLED=1

;TOGLIE GRADIENTE DA TASTI E STATUS PANEL E MENU SISTEMA
GRAD_ENABLED=0


;-------------------------------------------------------
; Settaggi bottoni orizzontali
;-------------------------------------------------------

[HOR_KEYS]

;HEIGHT=55
HEIGHT=100
SYSTEM_KEY_WIDTH=75

;## Default Values

BKG_COLOR=51,51,51
BKG_SEL_COLOR=153,153,153

TXT_COLOR=118,118,118
TXT_SEL_COLOR=0,0,0

BORDER_COLOR=51,51,51
BORDER_COLOR_ACTIVE=153,153,153
BORDER_THICK=1

CUSTOM_KEY_MENU = ..\\icone ppg\\Mainmenu\\Menu.png
CUSTOM_KEY_LEFT  =  ..\\icone ppg\\Mainmenu\\STK_LEFT.png
CUSTOM_KEY_LEFT_OFF  =  ..\\icone ppg\\Mainmenu\\STK_LEFT_OFF.png
CUSTOM_KEY_RIGHT  =  ..\\icone ppg\\Mainmenu\\STK_RIGHT.png
;CUSTOM_KEY_RIGHT_OFF  =  ..\\icone ppg\\Mainmenu\\STK_RIGHT_OFF.png
CUSTOM_KEY_MENU_DIS = ..\\icone ppg\\Mainmenu\\Menu.png


ROUNDNESS=0
COLOR_SKIN=51,51,51
GRAD_MODE_SKIN=0
TRANSP_KEY=1

;-------------------------------------------------------
; Settaggi bottoni verticali
;-------------------------------------------------------

[VERT_KEYS]

;Key_Width=100
;Key_Width=75
Key_Width=120

;## Default Values

BKG_COLOR=51,51,51
BKG_SEL_COLOR=153,153,153

TXT_COLOR=118,118,118
TXT_SEL_COLOR=0,0,0

BORDER_COLOR=51,51,51
BORDER_COLOR_ACTIVE=153,153,153
BORDER_THICK=1

ROUNDNESS=0
COLOR_SKIN=51,51,51
GRAD_MODE_SKIN=0
TRANSP_KEY=1

LED_ON=1
LED_EDGE=30

;-------------------------------------------------------
; Font bottoni orizzontali e verticali  (Solo Win)
;-------------------------------------------------------

; >> Font per tasti SENZA bitmap  <<
[PIC_FONT]           
FONT_NAME  = Arial
FONT_HEIGHT= 16
FONT_WIDTH = 6
FONT_BOLD  = 700


;>>  Font per tasti CON bitmap <<
[PICS_FONT]          
FONT_NAME  = Arial
FONT_HEIGHT= 16
FONT_WIDTH = 6
FONT_BOLD  = 700


;-------------------------------------------------------
; Settaggi Status Bar
;-------------------------------------------------------

[STATUS_BAR]
HEIGHT=58
BKG_COLOR=190,190,190

BKG_COLOR_TIME=60,111,190
TXT_COLOR_TIME=

BKG_COLOR_ALARM=190,190,190
TXT_COLOR_ALARM1=255,0,0
TXT_COLOR_ALARM2=255,0,0
TXT_COLOR_MSG=0,0,255

BKG_COLOR_CAPTION=190,190,190
TXT_COLOR_CAPTION=118,118,118

BKG_COLOR_ICON=190,190,190

LOGO_FILE_BMP=..\Kvara\Logo.png

;Colore sfondo status panel
COLOR_SKIN=51,51,51

;Gradiente abilitato
GRAD_MODE_SKIN=0

;Box trasparenti
TRANSP_BOX=1

;toglie limea rossa
RED_LINE=0
;-------------------------------------------------------
; Font Status Bar (solo Win)
;-------------------------------------------------------

[CAPTION_FONT]
FONT_NAME  = Arial
FONT_HEIGHT= 34
;FONT_WIDTH = 8
FONT_BOLD  = 800


[ALARMS_FONT]
FONT_NAME  = Arial
FONT_HEIGHT= 18
FONT_WIDTH = 12
FONT_BOLD  = 800


;-------------------------------------------------------
; Settaggi System Menu
;-------------------------------------------------------

[SYSTEM_MENU]

SYS_WIDTH=300

BKG_COLOR=51,51,51
BKG_SEL_COLOR=153,153,153


;** Colori Sys Menu (Sfondo, bordo e testo)
SYS_BKG_NORM_COLOR = 32,32,32  
SYS_EDG_NORM_COLOR = 32,32,32
SYS_TXT_NORM_COLOR = 204,204,204
SYS_BKG_SEL_COLOR  = 153,153,153
SYS_EDG_SEL_COLOR  = 153,153,153   
SYS_TXT_SEL_COLOR  = 0,0,0  


;** Colori Menu Contestuale (Sfondo, bordo e testo)
APP_BKG_NORM_COLOR = 32,32,32
APP_EDG_NORM_COLOR = 32,32,32
APP_TXT_NORM_COLOR = 204 ,204,204
APP_BKG_SEL_COLOR  = 153,153,153
APP_EDG_SEL_COLOR  = 153,153,153    
APP_TXT_SEL_COLOR  = 0,0,0  


[SYSMENU_FONT]
FONT_NAME  = Arial
FONT_HEIGHT= 26
FONT_WIDTH = 9
FONT_BOLD  = 500


// Utilizzati solo su monoboard

;-------------------------------------------------------
; Settaggi Status Bar di pagina
;-------------------------------------------------------

[STATUS_BAR_PAGE]
BKG_COLOR= 240,240,240
TXT_COLOR= 255,255,255

;-------------------------------------------------------
; Settaggi colore sfondo pagine di base
;-------------------------------------------------------

[DESK_PAGE]
BKG_COLOR=

;-------------------------------------------------------
; Settaggi colori dialog modali
;-------------------------------------------------------

[DESK_DIALOG]
BKG_COLOR=
TXT_COLOR=
BKG_COLOR_KEY=
TXT_COLOR_KEY=

BKG_COLOR_RECT_SELKEY=
BKG_COLOR_SELKEY=
TXT_COLOR_SELKEY=

[TOOLBAR]
BKG_COLOR_IMG = 51,51,51

[POPUP_MENU]
WIDTH=250