[COLOR]
;BKG_COLOR_KEY = 0,0,160
BKG_COLOR_KEY = 190,190,190
;TXT_COLOR_KEY = 255,255,255
TXT_COLOR_KEY = 0,0,0
;BKG_COLOR_SELKEY = 255,0,0
BKG_COLOR_SELKEY = 44,44,44
;TXT_COLOR_SELKEY = 255,255,0
TXT_COLOR_SELKEY = 255,255,255

BKG_COLOR_MENU = 190,190,190
TXT_COLOR_MENU = 0,0,0 
BKG_COLOR_SELMENU = 44,44,44
TXT_COLOR_SEL_MENU = 255,255,255


[DIMENSION]
DX_NUM=500
DY_NUM=330
DX_ALFA=544
DY_ALFA=475

DEF_DX_NUM=500
DEF_DY_NUM=330
DEF_DX_ALFA=625
DEF_DY_ALFA=353


