[SYS]
DEFCN=C:\DiscoH
IOREDIR=C:\DiscoH
LINK=NETWORK
TASKMTR=0
RDSIZE=16
SLAVEDBCHAN=0
CNWAIT=1
DRIVES=0x018C

[PLC]
TARDIR=c:\plc

[COM]
CLOSECHWAIT=1000
RESETCNDELAY=5000
SHUTDOWNCNDELAY=5000
RetainMode=1

[CHA.PATH]
PGM=C:\PGM
CFU=C:\CFU
CFS=C:\cfu
CFM=C:\cfu
MDI=C:\PGM
CFCDLL=C:\AutoDll
SLAPPG=C:\AutoDll\SlaPpg.dll
;CANSYS=C:\AutoDll\Cansys.dll
DGTDLL=C:\AutoDll\SlaCan.dll
SLAOSC=C:\AutoDll\SlaOsc.dll
SLADLL=C:\AutoDll\Sladll.dll
SLACOUP=C:\AutoDll\Slacoup.dll
USERDLL=C:\AutoDll\PilzSrv.dll
USERDLL1=C:\AutoDll\Puls\PulsCniSrv.dll
USERDLL2=C:\AutoDll\LazerSafe.dll
USERDLL3=C:\AutoDll\Pnoz.dll
USERDLL4=C:\AutoDll\Fpsc.dll
USERDLL5=C:\AutoDll\PilzUDP.dll
USERDLL6=C:\AutoDll\MCS.dll
USERDLL7=C:\AutoDll\LedsBar.dll
CVBDLL=$
APIODLL=$
PMIDLL=$
TMAPIDLL=$

[UIM.PATH]
MOTFILES=c:\motor

[HARDWARE]
;DGTDLL=RINGS.1,ADDR.0xDE000,IRQ.11    // Yaskawa
;CANSYS=RINGS.1,ADDR.0xD8000,IRQ.9,3

[CHA.EXT]
PGM=PGM
CFU=CFU
CFS=CFS
CFM=CFM
CST=CST

[ENV]
LOG=F:

[TASKMTR]
SLAVE_REGOL=0:220
SLAVE_CALC=1:180
PLCSLOW=2:160
PLCFAST=3:200
NCRUN=4:140
SLAVE_ISR=5:255
PLCMANAGER=6:250
DATALINK_SERVER=7:100
DATALINK_COM_SERVER=8:110
;FILE_TRANSFER_SERVER=10:60
;KRAS_SERVER=11:40
;PROGRAM_FLASH_SERVER=12:50
;PLCSUPERVISOR=13:230
;PLCCMD=14:80
;PLCSEREXE=15:75
;PLCSER=16:70
;SLAVE_DEBUG=17:90
;KVSCOPE_ISR=18:240

[PULSAUX]
PATH=C:\AutoDll\Puls

[PNOZMULTI]
Priority=1

[FPSCMULTI]
Priority=1

[PilzUDP]
ClientIPAddr=10.10.51.100
ClientIPPort=4713
ServerIPAddr=10.10.51.99
ServerIPPort=4711
MaxLenInput=20			; in byte
MaxLenOutput=20			; in byte
DllPriority=2		        ; priorità
DllSleep=20		        ; intervallo thread