* Phisical I/Os
* Inputs

#defcom %FUNCBTN.0  start button
#defcom %FUNCBTN.1  stop button
#defcom %FUNCBTN.2  + button
#defcom %FUNCBTN.3  - button

#defcom %C60.0    IN Press pedal
#defcom %C60.1    IN Rise pedal
#defcom %C60.2    IN Photocell activation
#defcom %C60.3    IN Front arms enabling
#defcom %C60.4    IN Slow manual rise
#defcom %C60.5    IN Photocell inhibited
#defcom %C60.6    IN General Emergency
#defcom %C60.7    IN Stop at BDC mode
#defcom %C60.8    IN Remote machine in automatic mode
#defcom %C60.9    IN Remote machine in semiautomatic mode
#defcom %C60.10   IN External START button
#defcom %C60.11   IN Rising to maximum TDC
#defcom %C60.12   IN Machining reset
#defcom %C60.13   IN Operation with robot
#defcom %C60.14   IN Machine in tandem selection
#defcom %C60.15   IN Remote machine at TDC
#defcom %C60.16   IN Remote machine at mute
#defcom %C60.17   IN Remote machine at pinch point
#defcom %C60.18   IN Remote machine at BDC
#defcom %C60.19   IN Remote machine at pinch before retract
#defcom %C60.20   IN Remote NC axes in position
#defcom %C60.21   IN Remote machine in alarm status
#defcom %C60.22   IN External STOP button
#defcom %C60.23   IN OPS crowning in progress
#defcom %C60.24   IN Lower clamp opening sel.
#defcom %C60.25   IN OID index in progress
#defcom %C60.26   IN GPS sensor calibration
#defcom %C60.27   IN Upper clamp opening sel.
#defcom %C60.28   IN External step change
#defcom %C60.29   IN Back gauge retract switch
#defcom %C60.30   IN Beam at TDC switch
#defcom %C60.31   IN Manual Z cycle enab. sel.

#defcom %C61.0    IN No air (NO)
#defcom %C61.1    IN bit 0 alarm code
#defcom %C61.2    IN bit 1 alarm code
#defcom %C61.3    IN bit 2 alarm code
#defcom %C61.4    IN bit 3 alarm code
#defcom %C61.5    IN Pump Thermal relay activation
#defcom %C61.6    IN X axis Drive alarm
#defcom %C61.7    IN R axis Drive alarm
#defcom %C61.8    IN Z1 axis Drive alarm
#defcom %C61.9    IN Z2 axis Drive alarm
#defcom %C61.10   IN Oil filter clogged alarm
#defcom %C61.11   IN External + button
#defcom %C61.12   IN External - button
#defcom %C61.13   IN A2 front arm enab.
#defcom %C61.14   IN No air (NC)
#defcom %C61.15   IN External Hand Wheel enabling button
#defcom %C61.16   IN Force Backgauge safety Speed at (2m/min)
#defcom %C61.17   IN 49
#defcom %C61.18   IN Maximum Unbalance switch
#defcom %C61.19   IN Valve Y1 Ascent direction
#defcom %C61.20   IN Valve Y2 Ascent direction
#defcom %C61.21   IN Valve Y1 Descent direction
#defcom %C61.22   IN Valve Y2 Descent direction
#defcom %C61.23   IN Slowing selector
#defcom %C61.24   IN Emergency descent
#defcom %C61.25   IN Cycle block via robot
#defcom %C61.26   IN Upper clamp pressure switch
#defcom %C61.27   IN Lower clamp pressure switch
#defcom %C61.28   IN Relay 20KA1,2,3,4 monitoring
#defcom %C61.29   IN valve A1 transducer
#defcom %C61.30   IN valve A2 transducer
#defcom %C61.31   IN Mute and BDC sync reset

#defcom %C62.0    IN Pump On
#defcom %C62.1    IN Side guards not closed
#defcom %C62.2    IN Safety SV transducer SQ1
#defcom %C62.3    IN Safety SV transducer SQ2
#defcom %C62.4    IN Edit mode selection from robot
#defcom %C62.5    IN Automatic mode selection from robot
#defcom %C62.6    IN Bit0 program code from robot
#defcom %C62.7    IN Bit1 program code from robot
#defcom %C62.8    IN Bit2 program code from robot
#defcom %C62.9    IN Bit3 program code from robot
#defcom %C62.10   IN Bit4 program code from robot
#defcom %C62.11   IN Drives OK
#defcom %C62.12   IN End of pressing 1
#defcom %C62.13   IN End of pressing 2
#defcom %C62.14   IN External mute
#defcom %C62.15   IN Stop at mute
#defcom %C62.16   IN Automatic mode selection from tandem
#defcom %C62.17   IN Fast Descent SV transducer SQ5
#defcom %C62.18   IN Fast Descent SV transducer SQ6
#defcom %C62.19   User Alarm 1
#defcom %C62.20   User Alarm 2
#defcom %C62.21   User Alarm 3
#defcom %C62.22   User Message 1
#defcom %C62.23   User Message 2
#defcom %C62.24   IN Prefillings SV transducer SQ7
#defcom %C62.25   IN Y1 transducer (Valve in OFF Position)
#defcom %C62.26   IN Y2 transducer (Valve in OFF Position)
#defcom %C62.27   IN Slow Down SV Transducer
#defcom %C62.28   IN Stop floatation from sensor
#defcom %C62.29   IN Y0 axis calibration switch
#defcom %C62.30   IN Manual mode selection from tandem
#defcom %C62.31   IN Semiauto. mode selection from tandem

#defcom %C63.0    IN Second mute selection
#defcom %C63.1    IN 97
#defcom %C63.2    IN 98
#defcom %C63.3    IN 99
#defcom %C63.4    IN Bit5 program code from robot
#defcom %C63.5    IN Bit6 program code from robot
#defcom %C63.6    IN Bit7 program code from robot
#defcom %C63.7    IN Enable Hand Wheel x10 (0.1mm)
#defcom %C63.8    IN Enable Hand Wheel x100 (1mm)
#defcom %C63.9    IN Enable Hand Wheel Acquisition
#defcom %C63.10   IN Selection Y1 for Hand Wheel Acquisition
#defcom %C63.11   IN Selection Y2 for Hand Wheel Acquisition
#defcom %C63.12   IN 108
#defcom %C63.13   IN 109
#defcom %C63.14   IN 110
#defcom %C63.15   IN 111
#defcom %C63.16   IN 112
#defcom %C63.17   IN 113
#defcom %C63.18   IN 114
#defcom %C63.19   IN 115
#defcom %C63.20   IN 116
#defcom %C63.21   IN 117
#defcom %C63.22   IN 118
#defcom %C63.23   IN 119
#defcom %C63.24   IN 120
#defcom %C63.25   IN 121
#defcom %C63.26   IN 122
#defcom %C63.27   IN 123
#defcom %C63.28   IN 124
#defcom %C63.29   IN 125
#defcom %C63.30   IN 126
#defcom %C63.31   IN 127

#defcom %C64.0    IN 128
#defcom %C64.1    IN 129
#defcom %C64.2    IN 130
#defcom %C64.3    IN 131
#defcom %C64.4    IN 132
#defcom %C64.5    IN 133
#defcom %C64.6    IN 134
#defcom %C64.7    IN 135
#defcom %C64.8    IN 136
#defcom %C64.9    IN 137
#defcom %C64.10   IN 138
#defcom %C64.11   IN 139
#defcom %C64.12   IN 140
#defcom %C64.13   IN 141
#defcom %C64.14   IN 142
#defcom %C64.15   IN 143
#defcom %C64.16   IN 144
#defcom %C64.17   IN 145
#defcom %C64.18   IN 146
#defcom %C64.19   IN 147
#defcom %C64.20   IN 148
#defcom %C64.21   IN 149

#defcom %C64      IN Configurable (first 21 bit)

* Ingressi analogici

#defcom %C68      (IW20) Strain gauge left side (0-4095) or Potentiometric pedal analog
#defcom %C69      (IW21) Strain gauge right side (0-4095)

#defcom %C82      IN Pressure sensor Cylinder 1
#defcom %C83      IN Pressure sensor Cylinder 2
#defcom %C84      IN Pressure sensor Main Pump

#defcom %C95      IN (IW90) Cursor position Y1 Valve (0-4095)
#defcom %C96      IN (IW91) Cursor position Y2 Valve (0-4095)
#defcom %C97      IN Crowning pressure sensor

* Uscite

#defcom %C70.0    OUT Function 1
#defcom %C70.1    OUT Function 2 (Pneum.flatten.\Step change at TDC)
#defcom %C70.2    OUT Function 3 (Z axes retract)
#defcom %C70.3    OUT Function 4 (Front arm unhook cycle enab.)
#defcom %C70.4    OUT CNC in automatic mode
#defcom %C70.5    OUT CNC in semiautomatic mode
#defcom %C70.6    OUT CNC in manual mode
#defcom %C70.7    OUT CNC OK
#defcom %C70.8    OUT Valve 1
#defcom %C70.9    OUT Valve 2
#defcom %C70.10   OUT Valve 3
#defcom %C70.11   OUT Valve 4
#defcom %C70.12   OUT Valve 5
#defcom %C70.13   OUT Valve 6
#defcom %C70.14   OUT Valve 7
#defcom %C70.15   OUT Valve 8
#defcom %C70.16   OUT Machine at TDC
#defcom %C70.17   OUT Machine at mute (photocell inhibition)
#defcom %C70.18   OUT Machine at pinch point
#defcom %C70.19   OUT Machine at BDC
#defcom %C70.20   OUT Machine at pinch point before retract
#defcom %C70.21   OUT Axes in position
#defcom %C70.22   OUT NC in alarm status
#defcom %C70.23   OUT Bit0 program code to robot
#defcom %C70.24   OUT Bit1 program code to robot
#defcom %C70.25   OUT Bit2 program code to robot
#defcom %C70.26   OUT Bit3 program code to robot
#defcom %C70.27   OUT Bit4 program code to robot
#defcom %C70.28   OUT RALL activation
#defcom %C70.29   OUT POS activation
#defcom %C70.30   OUT IND activation
#defcom %C70.31   OUT DCP activation

#defcom %C71.0    OUT FORK activation 
#defcom %C71.1    OUT Punch release valve
#defcom %C71.2    OUT Manual Z release valve
#defcom %C71.3    OUT A1-A2 pressure on/off valve
#defcom %C71.4    OUT A1-A2 descent on/off valve
#defcom %C71.5    OUT Synchro control
#defcom %C71.6    OUT Finished wkp
#defcom %C71.7    OUT Dies release valve
#defcom %C71.8    OUT Cut-out photocells 5mm before pinch
#defcom %C71.9    OUT Beam enable in microswitch machine
#defcom %C71.10   OUT Edit mode selection to robot
#defcom %C71.11   OUT Automatic mode selection to robot
#defcom %C71.12   OUT CNC ready down (Ram descent enabled)
#defcom %C71.13   OUT UP command LZS (ascent)
#defcom %C71.14   OUT Decompression active
#defcom %C71.15   OUT CNC in Autotuning
#defcom %C71.16   OUT Change Speed before TDC
#defcom %C71.17   OUT VCreep speed
#defcom %C71.18   OUT Upper clamps open indicator light 
#defcom %C71.19   OUT Lower clamps open indicator light 
#defcom %C71.20   OUT Slow descent indicator light
#defcom %C71.21   OUT Hydraulic cushion pressure SV
#defcom %C71.22   OUT Crowning valves piloting
#defcom %C71.23   OUT START button output
#defcom %C71.24   OUT STOP button output
#defcom %C71.25   OUT + button output
#defcom %C71.26   OUT - button output
#defcom %C71.27   OUT Descent enabling
#defcom %C71.28   OUT Slow rise to pinch point in progress
#defcom %C71.29   OUT Stopping space procedure management opt.
#defcom %C71.30   OUT Upper clamp management opt.
#defcom %C71.31   OUT Lower clamp management opt.

#defcom %C72.0    OUT Proportional direction error
#defcom %C72.1    OUT Upper clamps 2 management opt. 
#defcom %C72.2    OUT Fiessler management opt.
#defcom %C72.3    OUT Double pedal board management opt.
#defcom %C72.4    OUT Follower management opt.
#defcom %C72.5    OUT Function 5 (slow descent)
#defcom %C72.6    OUT Function 6 (lh pedal board selection)
#defcom %C72.7    OUT Function 7 (Fiessler safety system)
#defcom %C72.8    OUT Function 8 (type of crowning)
#defcom %C72.9    OUT Function 9 (Step Change at BDC)
#defcom %C72.10   OUT Function 10
#defcom %C72.11   OUT Function 11
#defcom %C72.12   OUT Function 12
#defcom %C72.13   OUT Function 13
#defcom %C72.14   OUT Function 14
#defcom %C72.15   OUT Function 15
#defcom %C72.16   OUT Function 16
#defcom %C72.17   OUT Function 17
#defcom %C72.18   OUT Function 18
#defcom %C72.19   OUT Function 19
#defcom %C72.20   OUT Function 20
#defcom %C72.21   OUT Maximum Unbalance
#defcom %C72.22   OUT Wait for Bend Time in progress
#defcom %C72.23   OUT Up to TDC command (Conventional)
#defcom %C72.24   OUT End of Decompression
#defcom %C72.25   OUT Punch block valve
#defcom %C72.26   OUT Die block valve
#defcom %C72.27   OUT Machine referenced
#defcom %C72.28   OUT Die function F1
#defcom %C72.29   OUT Die function F2
#defcom %C72.30   OUT Die function F3
#defcom %C72.31   OUT Die function F4

#defcom %C73.0    OUT Die function F5
#defcom %C73.1    OUT Die function F6
#defcom %C73.2    OUT Cycle active
#defcom %C73.3    OUT Cycle not active
#defcom %C73.4    OUT Pump ON 100
#defcom %C73.5    OUT Second Mute Point (Akas3pm) OUT 101
#defcom %C73.6    OUT Bit5 program code for robot OUT 102
#defcom %C73.7    OUT Bit6 program code for robot OUT 103
#defcom %C73.8    OUT Bit7 program code for robot OUT 104
#defcom %C73.9    OUT 105
#defcom %C73.10   OUT 106
#defcom %C73.11   OUT 107
#defcom %C73.12   OUT 108
#defcom %C73.13   OUT 109
#defcom %C73.14   OUT 110
#defcom %C73.15   OUT 111
#defcom %C73.16   OUT 112
#defcom %C73.17   OUT 113
#defcom %C73.18   OUT 114
#defcom %C73.19   OUT 115
#defcom %C73.20   OUT 116
#defcom %C73.21   OUT 117
#defcom %C73.22   OUT 118
#defcom %C73.23   OUT 119
#defcom %C73.24   OUT 120
#defcom %C73.25   OUT 121
#defcom %C73.26   OUT 122
#defcom %C73.27   OUT 123
#defcom %C73.28   OUT 124
#defcom %C73.29   OUT 125
#defcom %C73.30   OUT 126
#defcom %C73.31   OUT 127

#defcom %C93.0    OUT 128
#defcom %C93.1    OUT 129
#defcom %C93.2    OUT 130
#defcom %C93.3    OUT 131
#defcom %C93.4    OUT 132
#defcom %C93.5    OUT 133
#defcom %C93.6    OUT 134
#defcom %C93.7    OUT 135
#defcom %C93.8    OUT 136
#defcom %C93.9    OUT 137
#defcom %C93.10   OUT 138
#defcom %C93.11   OUT 139
#defcom %C93.12   OUT 140
#defcom %C93.13   OUT 141
#defcom %C93.14   OUT 142
#defcom %C93.15   OUT 143
#defcom %C93.16   OUT 144
#defcom %C93.17   OUT 145
#defcom %C93.18   OUT 146
#defcom %C93.19   OUT 147
#defcom %C93.20   OUT 148
#defcom %C93.21   OUT 149

* Uscite analogiche

#defcom %C74      OUT (QW207) Y1 Descent current command
#defcom %C75      OUT (QW209) Y2 Descent current command
#defcom %C76      OUT (QW206) Y1 Ascent current command
#defcom %C77      OUT (QW208) Y2 Ascent current command

#defcom %C78      OUT (QW100) Pressure command
#defcom %C79      OUT (QW101) Crowning command
#defcom %fs0      OUT (QW200) Pressure command full scale
#defcom %fs1      OUT (QW201) Crowning command full scale

#defcom %C85      OUT (QW210) PWM Frequency

#defcom %C86      OUT (QW211) Y1 simulated output from slave (14 bit + direction)
#defcom %C87      OUT (QW212) Y2 simulated output from slave (14 bit + direction)
#defcom %C88      OUT (QW204) Y1 valve command (14 bit + direction)
#defcom %C89      OUT (QW205) Y2 valve command (14 bit + direction)

#defcom %C93      OUT configurable (first 21 bit)
